# Generated by Django 3.2.15 on 2022-10-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='owner_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
