# Generated by Django 3.2.15 on 2022-10-19 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_owner_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='owner_name',
        ),
    ]
